### ISSUE TITLE
L10N with Transifex

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/flyve-mdm-ios-inventory-agent#3]
Hi @hectorerb 

Please generate the file for all strings to upload on Transifex.com.

- https://docs.transifex.com/formats/apple-plist
- https://docs.transifex.com/formats/apple-strings
- https://docs.transifex.com/formats/stringsdict

Thanks

**Comment by hectorerb** [comment]
@ajsb85 perfect!

**Comment by ajsb85** [comment]
Already uploaded the resources to Transifex
https://www.transifex.com/flyve-mdm/flyve-mdm-ios-inventory-agent/l

**Comment by ajsb85** [comment]
Hi, @hectorerb 

Please remove the organization and this project:

https://www.transifex.com/teclib-3/fusioninventory-ios/

I added you as Project Maintainer on Transifex

https://www.transifex.com/flyve-mdm/flyve-mdm-ios-inventory-agent/
