### ISSUE TITLE
Apple Store images

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/flyve-mdm-ios-inventory-agent#6]
Hi @hectorerb 
Could you provide the properties of the images for apple store?

@mmillevoye Can help us wiht that.

Salut.

**Comment by hectorerb** [comment]
@ajsb85 The app icon is required at 1024x1024

**Comment by mmillevoye** [comment]
Hello, Is that what you need ?
![iconflyve](https://user-images.githubusercontent.com/29282308/27677833-48471e86-5cb3-11e7-8409-2bde4e15ec80.png)

**Comment by ajsb85** [comment]
@mmillevoye Good icon for the Flyve MDM.
But we need the iconography for FusionInventory

**Comment by mmillevoye** [comment]
Here it is :)
![fusioninventoryicon](https://user-images.githubusercontent.com/29282308/27678375-4c5d11d6-5cb5-11e7-9691-ef6d5e066bab.jpg)

**Comment by ajsb85** [comment]
[FusionInventory-iOS.psd.zip](https://github.com/flyve-mdm/fusioninventory-ios/files/1111638/FusionInventory-iOS.psd.zip)
![fusioninventory](https://user-images.githubusercontent.com/663460/27683176-669481d2-5cc5-11e7-9128-3870c9429564.png)

**Comment by ajsb85** [comment]
[FusionInventory-iOS.psd.zip](https://github.com/flyve-mdm/fusioninventory-ios/files/1111642/FusionInventory-iOS.psd.zip)
![fusioninventory](https://user-images.githubusercontent.com/663460/27683192-74adbc0c-5cc5-11e7-92cd-9dd8e6ef03a5.png)

**Comment by hectorerb** [comment]
@mmillevoye thanks! Very good but the icon should be square

**Comment by ajsb85** [comment]
I will create a new one right now.

**Comment by mmillevoye** [comment]
![icon-flyve](https://user-images.githubusercontent.com/29282308/27739291-58c47a82-5dae-11e7-9205-db663ea93ab1.png)
Done :)

**Comment by ajsb85** [comment]
@mmillevoye Merci !
